Assignment 7

In [1]:
#1.	Write a Python Program to find sum of array?
import numpy as np
a1 = np.arange(0,20,1)
sum =0
for i in range (0,len(a1)):
    sum=sum+a1[i]
print('sum of the arrray is ',sum)

sum of the arrray is  190


In [2]:
#2.	Write a Python Program to find largest element in an array?
import numpy as np
a1 = np.arange(0,20,1)
m=max(a1)
print(m)

19


In [3]:
#3.	Write a Python Program for array rotation?
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#4.	Write a Python Program to Split the array and add the first part to the end?
import numpy as np
a1=np.array([[2,3],[4,5],[6,7],[8,9]])
a2=a1[...,1:]
arr=np.hstack((a1,a2))
arr

array([[2, 3, 3],
       [4, 5, 5],
       [6, 7, 7],
       [8, 9, 9]])

In [ ]:
#5.	Write a Python Program to check if given array is Monotonic?
def check(a):
    return (all (a[i]<=a[i+1] for i in range (len(a)-1)) or
            all (a[i]>=a[i+1] for i in range (len(a)-1)))
a =[6,5,4,3]
print(check(a))

Assignment 8

In [ ]:
#1.	Write a Python Program to Add Two Matrices?
import numpy as np
a1 = np.mat([[2,3],[4,6]])
a2 = np.mat([[34,21],[43,12]])
print(np.add(a1,a2))

In [ ]:
#2.	Write a Python Program to Multiply Two Matrices?
import numpy as np
a1 = np.mat([[2,3],[4,6]])
a2 = np.mat([[34,21],[43,12]])
a3 = np.mat([[0,0],[0,0]])
a3 = a1*a2
print(a3)

In [ ]:
#3.	Write a Python Program to Transpose a Matrix?
import numpy as np
a1 = np.mat([[2,3],[4,6]])
print(np.transpose(a1))

In [ ]:
#4.	Write a Python Program to Sort Words in Alphabetic Order?
wrd = 'Charles Brown was an American blues singer and pianist whose soft-toned'
word = [w for w in wrd.split()]
word.sort()
for w in word:
    print(w)

In [ ]:
#5.	Write a Python Program to Remove Punctuation From a String?
s ='Charles Brown (September 13, 1922 – January 21, 1999) was an American blues singer and pianist whose soft-toned, slow-paced blues-club style influenced blues performance in the 1940s and 1950s.'
punc =',-()–'
for i in s:
    if i in punc:
        s =s.replace(i,' ')
print(s)